In [89]:
# import standard libraries
import os
import pandas as pd
import sys
import numpy as np
import scipy as sp
import sklearn as sk
import itertools
import math

In [2]:
# get slice names
path_stem = "/Users/danielagarcia/OneDrive - Harvard University/Sophomore Year/CS109a/jupyter/cs109a-final-project/Data/data/"
file_names = os.listdir(path_stem)
assert len(file_names) == 1000

In [3]:
# create empty data frame to store concatenated slices
playlist_data_raw = pd.DataFrame()

# combine each slice into one data frame 
for file in file_names:
    data_temp = pd.read_csv(path_stem + file)
    playlist_data_raw = playlist_data_raw.append(data_temp, ignore_index = True)

In [4]:
# view first five rows of full data frame
display(playlist_data_raw.head())

,Unnamed: 0,name,collaborative,pid,modified_at,num_tracks,num_albums,num_followers,tracks,num_edits,duration_ms,num_artists,description
0,0,2014,False,292000,1509235200,88,58,16,"[{'pos': 0, 'artist_name': 'Ty Dolla $ign', 't...",40,18032849,55,NaN
1,1,Backyard BBQ,False,292001,1502582400,116,109,1,"[{'pos': 0, 'artist_name': 'Matt and Kim', 'tr...",11,25842835,82,NaN
2,2,old school,False,292002,1442534400,103,60,2,"[{'pos': 0, 'artist_name': 'Lil Wayne', 'track...",12,26331174,41,NaN
3,3,Broken,False,292003,1502236800,172,138,1,"[{'pos': 0, 'artist_name': 'Heather Headley', ...",23,46857118,106,NaN
4,4,travel,False,292004,1473811200,37,30,1,"[{'pos': 0, 'artist_name': 'Of Monsters and Me...",4,8241213,28,NaN

In [ ]:
# save data 
playlist_data_raw_file = "/Users/danielagarcia/OneDrive - Harvard University/Sophomore Year/CS109a/jupyter/cs109a-final-project/Data/playlist_data_raw.csv"
playlist_data_raw.to_csv(playlist_data_raw_file)